### ISSUE TITLE
NotImplementedError when searching for text in given url

### ISSUE THREAD

**Issue by SonnyBA** [maykinmedia/python-textmatcher#1]
When searching for text in the given url e.g:
```
text_to_match = justification.justification
ratio = match(justification.link, text_to_match)
```
a NotImplementedError is raised:
```
Traceback (most recent call last):
  File "../../../src/manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/home/sonny/.virtualenvs/kieskompas/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/sonny/.virtualenvs/kieskompas/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File Traceback (most recent call last):
  File "../../../src/manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/home/sonny/.virtualenvs/kieskompas/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/sonny/.virtualenvs/kieskompas/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/sonny/.virtualenvs/kieskompas/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/sonny/.virtualenvs/kieskompas/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/sonny/Development/kieskompas/src/kieskompas/party_input/management/commands/scan_new_entries.py", line 44, in handle
    ratio = match(justification.link, text_to_match)
  File "/home/sonny/.virtualenvs/kieskompas/lib/python3.6/site-packages/textmatcher/program.py", line 97, in match
    text_data = get_text_data(url)
  File "/home/sonny/.virtualenvs/kieskompas/lib/python3.6/site-packages/textmatcher/program.py", line 41, in get_text_data
    raise NotImplementedError('There is no implementation for {}!'.format(response.headers['Content-Type']))
NotImplementedError: There is no implementation for text/html; charset=utf-8!"/home/sonny/.virtualenvs/kieskompas/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/sonny/.virtualenvs/kieskompas/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/sonny/Development/kieskompas/src/kieskompas/party_input/management/commands/scan_new_entries.py", line 44, in handle
    ratio = match(justification.link, text_to_match)
  File "/home/sonny/.virtualenvs/kieskompas/lib/python3.6/site-packages/textmatcher/program.py", line 97, in match
    text_data = get_text_data(url)
  File "/home/sonny/.virtualenvs/kieskompas/lib/python3.6/site-packages/textmatcher/program.py", line 41, in get_text_data
    raise NotImplementedError('There is no implementation for {}!'.format(response.headers['Content-Type']))
NotImplementedError: There is no implementation for text/html; charset=utf-8!
```

**Comment by JoseJBoon** [comment]
get_text_data now takes into account that a charset maybe added to the content-type.
